RBE 2000 level template code: GetIMU Class Reference
GetIMU Class Reference
#include <GetIMU.h>
Public Member Functions
GetIMU ()
void event (float *buffer)
boolean loop ()
void startSensor (Adafruit_BNO055 *_bno)
void print ()
float getLINEARACCEL_X ()
float getLINEARACCEL_Y ()
float getLINEARACCEL_Z ()
float getGYROSCOPE_X ()
float getGYROSCOPE_Y ()
float getGYROSCOPE_Z ()
float getGRAVITY_X ()
float getGRAVITY_Y ()
float getGRAVITY_Z ()
float getEULER_azimuth ()
float getEULER_elevation ()
float getEULER_tilt ()
float getXPosition ()
float getYPosition ()
float getZPosition ()
void setXPosition (float x)
void setYPosition (float y)
void setZPosition (float z)
Private Attributes
Adafruit_BNO055 * bno
volatile float bufferINTERNAL [NUM_IMU_VALUES]
bool started
int updateIndex =0
float absoluteRotation =0
float lastRotation =0
bool firstRotationRead =true
Detailed Description
Definition at line 18 of file GetIMU.h.
Constructor & Destructor Documentation
GetIMU::GetIMU () inline
Definition at line 33 of file GetIMU.h.
References event(), getEULER_azimuth(), getEULER_elevation(), getEULER_tilt(), getGRAVITY_X(), getGRAVITY_Y(), getGRAVITY_Z(), getGYROSCOPE_X(), getGYROSCOPE_Y(), getGYROSCOPE_Z(), getLINEARACCEL_X(), getLINEARACCEL_Y(), getLINEARACCEL_Z(), getXPosition(), getYPosition(), getZPosition(), loop(), print(), setXPosition(), setYPosition(), setZPosition(), and startSensor().
Member Function Documentation
void GetIMU::event (float * buffer)
Definition at line 13 of file GetIMU.cpp.
References bufferINTERNAL, NUM_IMU_VALUES, and started.
Referenced by GetIMU().
float GetIMU::getEULER_azimuth ()
Definition at line 119 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getEULER_elevation ()
Definition at line 122 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getEULER_tilt ()
Definition at line 125 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGRAVITY_X ()
Definition at line 110 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGRAVITY_Y ()
Definition at line 113 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGRAVITY_Z ()
Definition at line 116 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGYROSCOPE_X ()
Definition at line 101 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGYROSCOPE_Y ()
Definition at line 104 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGYROSCOPE_Z ()
Definition at line 107 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getLINEARACCEL_X ()
Definition at line 92 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getLINEARACCEL_Y ()
Definition at line 95 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getLINEARACCEL_Z ()
Definition at line 98 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getXPosition ()
Definition at line 74 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getYPosition ()
Definition at line 77 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getZPosition ()
Definition at line 80 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
boolean GetIMU::loop ()
Definition at line 22 of file GetIMU.cpp.
References absoluteRotation, bno, bufferINTERNAL, firstRotationRead, lastRotation, started, and updateIndex.
Referenced by GetIMU(), and RobotControlCenter::loop().
void GetIMU::print ()
Definition at line 136 of file GetIMU.cpp.
References bufferINTERNAL, and started.
Referenced by GetIMU(), and StudentsRobot::updateStateMachine().
void GetIMU::setXPosition (float x)
Definition at line 83 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU(), and StudentsRobot::StudentsRobot().
void GetIMU::setYPosition (float y)
Definition at line 86 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU(), and StudentsRobot::StudentsRobot().
void GetIMU::setZPosition (float z)
Definition at line 89 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU(), and StudentsRobot::StudentsRobot().
void GetIMU::startSensor (Adafruit_BNO055 * _bno)
Definition at line 129 of file GetIMU.cpp.
References bno, and started.
Referenced by GetIMU(), and RobotControlCenter::setup().
Field Documentation
float GetIMU::absoluteRotation =0 private
Definition at line 28 of file GetIMU.h.
Referenced by loop().
Adafruit_BNO055* GetIMU::bno private
Definition at line 20 of file GetIMU.h.
Referenced by loop(), and startSensor().
volatile float GetIMU::bufferINTERNAL[NUM_IMU_VALUES] private
Definition at line 25 of file GetIMU.h.
Referenced by event(), getEULER_azimuth(), getEULER_elevation(), getEULER_tilt(), getGRAVITY_X(), getGRAVITY_Y(), getGRAVITY_Z(), getGYROSCOPE_X(), getGYROSCOPE_Y(), getGYROSCOPE_Z(), getLINEARACCEL_X(), getLINEARACCEL_Y(), getLINEARACCEL_Z(), getXPosition(), getYPosition(), getZPosition(), loop(), print(), setXPosition(), setYPosition(), and setZPosition().
bool GetIMU::firstRotationRead =true private
Definition at line 30 of file GetIMU.h.
Referenced by loop().
float GetIMU::lastRotation =0 private
Definition at line 29 of file GetIMU.h.
Referenced by loop().
bool GetIMU::started private
Definition at line 26 of file GetIMU.h.
Referenced by event(), loop(), print(), and startSensor().
int GetIMU::updateIndex =0 private
Definition at line 27 of file GetIMU.h.
Referenced by loop().
The documentation for this class was generated from the following files:
src/commands/GetIMU.h
src/commands/GetIMU.cpp